require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WorkflowStatusesController do

  # This should return the minimal set of attributes required to create a valid
  # WorkflowStatus. As you add validations to WorkflowStatus, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "title" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkflowStatusesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all workflow_statuses as @workflow_statuses" do
      workflow_status = WorkflowStatus.create! valid_attributes
      get :index, {}, valid_session
      assigns(:workflow_statuses).should eq([workflow_status])
    end
  end

  describe "GET show" do
    it "assigns the requested workflow_status as @workflow_status" do
      workflow_status = WorkflowStatus.create! valid_attributes
      get :show, {:id => workflow_status.to_param}, valid_session
      assigns(:workflow_status).should eq(workflow_status)
    end
  end

  describe "GET new" do
    it "assigns a new workflow_status as @workflow_status" do
      get :new, {}, valid_session
      assigns(:workflow_status).should be_a_new(WorkflowStatus)
    end
  end

  describe "GET edit" do
    it "assigns the requested workflow_status as @workflow_status" do
      workflow_status = WorkflowStatus.create! valid_attributes
      get :edit, {:id => workflow_status.to_param}, valid_session
      assigns(:workflow_status).should eq(workflow_status)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new WorkflowStatus" do
        expect {
          post :create, {:workflow_status => valid_attributes}, valid_session
        }.to change(WorkflowStatus, :count).by(1)
      end

      it "assigns a newly created workflow_status as @workflow_status" do
        post :create, {:workflow_status => valid_attributes}, valid_session
        assigns(:workflow_status).should be_a(WorkflowStatus)
        assigns(:workflow_status).should be_persisted
      end

      it "redirects to the created workflow_status" do
        post :create, {:workflow_status => valid_attributes}, valid_session
        response.should redirect_to(WorkflowStatus.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved workflow_status as @workflow_status" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkflowStatus.any_instance.stub(:save).and_return(false)
        post :create, {:workflow_status => { "title" => "invalid value" }}, valid_session
        assigns(:workflow_status).should be_a_new(WorkflowStatus)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        WorkflowStatus.any_instance.stub(:save).and_return(false)
        post :create, {:workflow_status => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested workflow_status" do
        workflow_status = WorkflowStatus.create! valid_attributes
        # Assuming there are no other workflow_statuses in the database, this
        # specifies that the WorkflowStatus created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        WorkflowStatus.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => workflow_status.to_param, :workflow_status => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested workflow_status as @workflow_status" do
        workflow_status = WorkflowStatus.create! valid_attributes
        put :update, {:id => workflow_status.to_param, :workflow_status => valid_attributes}, valid_session
        assigns(:workflow_status).should eq(workflow_status)
      end

      it "redirects to the workflow_status" do
        workflow_status = WorkflowStatus.create! valid_attributes
        put :update, {:id => workflow_status.to_param, :workflow_status => valid_attributes}, valid_session
        response.should redirect_to(workflow_status)
      end
    end

    describe "with invalid params" do
      it "assigns the workflow_status as @workflow_status" do
        workflow_status = WorkflowStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkflowStatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => workflow_status.to_param, :workflow_status => { "title" => "invalid value" }}, valid_session
        assigns(:workflow_status).should eq(workflow_status)
      end

      it "re-renders the 'edit' template" do
        workflow_status = WorkflowStatus.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        WorkflowStatus.any_instance.stub(:save).and_return(false)
        put :update, {:id => workflow_status.to_param, :workflow_status => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested workflow_status" do
      workflow_status = WorkflowStatus.create! valid_attributes
      expect {
        delete :destroy, {:id => workflow_status.to_param}, valid_session
      }.to change(WorkflowStatus, :count).by(-1)
    end

    it "redirects to the workflow_statuses list" do
      workflow_status = WorkflowStatus.create! valid_attributes
      delete :destroy, {:id => workflow_status.to_param}, valid_session
      response.should redirect_to(workflow_statuses_url)
    end
  end

end
