require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe StoryTypesController do

  # This should return the minimal set of attributes required to create a valid
  # StoryType. As you add validations to StoryType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "project" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # StoryTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all story_types as @story_types" do
      story_type = StoryType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:story_types).should eq([story_type])
    end
  end

  describe "GET show" do
    it "assigns the requested story_type as @story_type" do
      story_type = StoryType.create! valid_attributes
      get :show, {:id => story_type.to_param}, valid_session
      assigns(:story_type).should eq(story_type)
    end
  end

  describe "GET new" do
    it "assigns a new story_type as @story_type" do
      get :new, {}, valid_session
      assigns(:story_type).should be_a_new(StoryType)
    end
  end

  describe "GET edit" do
    it "assigns the requested story_type as @story_type" do
      story_type = StoryType.create! valid_attributes
      get :edit, {:id => story_type.to_param}, valid_session
      assigns(:story_type).should eq(story_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new StoryType" do
        expect {
          post :create, {:story_type => valid_attributes}, valid_session
        }.to change(StoryType, :count).by(1)
      end

      it "assigns a newly created story_type as @story_type" do
        post :create, {:story_type => valid_attributes}, valid_session
        assigns(:story_type).should be_a(StoryType)
        assigns(:story_type).should be_persisted
      end

      it "redirects to the created story_type" do
        post :create, {:story_type => valid_attributes}, valid_session
        response.should redirect_to(StoryType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved story_type as @story_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        StoryType.any_instance.stub(:save).and_return(false)
        post :create, {:story_type => { "project" => "invalid value" }}, valid_session
        assigns(:story_type).should be_a_new(StoryType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        StoryType.any_instance.stub(:save).and_return(false)
        post :create, {:story_type => { "project" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested story_type" do
        story_type = StoryType.create! valid_attributes
        # Assuming there are no other story_types in the database, this
        # specifies that the StoryType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        StoryType.any_instance.should_receive(:update).with({ "project" => "" })
        put :update, {:id => story_type.to_param, :story_type => { "project" => "" }}, valid_session
      end

      it "assigns the requested story_type as @story_type" do
        story_type = StoryType.create! valid_attributes
        put :update, {:id => story_type.to_param, :story_type => valid_attributes}, valid_session
        assigns(:story_type).should eq(story_type)
      end

      it "redirects to the story_type" do
        story_type = StoryType.create! valid_attributes
        put :update, {:id => story_type.to_param, :story_type => valid_attributes}, valid_session
        response.should redirect_to(story_type)
      end
    end

    describe "with invalid params" do
      it "assigns the story_type as @story_type" do
        story_type = StoryType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StoryType.any_instance.stub(:save).and_return(false)
        put :update, {:id => story_type.to_param, :story_type => { "project" => "invalid value" }}, valid_session
        assigns(:story_type).should eq(story_type)
      end

      it "re-renders the 'edit' template" do
        story_type = StoryType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        StoryType.any_instance.stub(:save).and_return(false)
        put :update, {:id => story_type.to_param, :story_type => { "project" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested story_type" do
      story_type = StoryType.create! valid_attributes
      expect {
        delete :destroy, {:id => story_type.to_param}, valid_session
      }.to change(StoryType, :count).by(-1)
    end

    it "redirects to the story_types list" do
      story_type = StoryType.create! valid_attributes
      delete :destroy, {:id => story_type.to_param}, valid_session
      response.should redirect_to(story_types_url)
    end
  end

end
